export const Colors = {
  surface: '#f7f3eb',
  surfaceDim: '#ded9d1',
  surfaceBright: '#fffaf2',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f1ece4',
  surfaceContainer: '#e8e2d9',
  surfaceContainerHigh: '#ded6cd',
  surfaceContainerHighest: '#d2c8bf',
  onSurface: '#211b18',
  onSurfaceVariant: '#604a45',
  inverseSurface: '#2f2926',
  inverseOnSurface: '#f7f3eb',
  outline: '#8f6f68',
  outlineVariant: '#dcc0ba',
  surfaceTint: '#c51f12',
  primary: '#c51f12',
  onPrimary: '#ffffff',
  primaryContainer: '#a8190f',
  onPrimaryContainer: '#ffe7df',
  inversePrimary: '#ffb4a8',
  secondary: '#735300',
  onSecondary: '#ffffff',
  secondaryContainer: '#f4e784',
  onSecondaryContainer: '#4b3900',
  tertiary: '#9f3a39',
  onTertiary: '#ffffff',
  tertiaryContainer: '#d78f8c',
  onTertiaryContainer: '#3f1412',
  error: '#ba1a1a',
  onError: '#ffffff',
  errorContainer: '#ffdad6',
  onErrorContainer: '#93000a',
  primaryFixed: '#ffdad3',
  primaryFixedDim: '#ffb4a8',
  onPrimaryFixed: '#410001',
  onPrimaryFixedVariant: '#8e140a',
  secondaryFixed: '#fff0a9',
  secondaryFixedDim: '#e6cf52',
  onSecondaryFixed: '#231b00',
  onSecondaryFixedVariant: '#584200',
  tertiaryFixed: '#ffdad7',
  tertiaryFixedDim: '#e9a5a1',
  onTertiaryFixed: '#3f1412',
  onTertiaryFixedVariant: '#7f2c2b',
  background: '#f0eee8',
  onBackground: '#211b18',
  surfaceVariant: '#e7d9d4',
  success: '#2e7d32',
  successContainer: '#dff2d8',
  onSuccessContainer: '#17451a',
  warning: '#a86600',
  warningContainer: '#fff0bd',
  onWarningContainer: '#523500',
} as const;

export const Shadow = {
  card: {
    shadowColor: '#211b18',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.07,
    shadowRadius: 18,
    elevation: 2,
  },
  fab: {
    shadowColor: '#c51f12',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.22,
    shadowRadius: 18,
    elevation: 6,
  },
  sheet: {
    shadowColor: '#211b18',
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.14,
    shadowRadius: 28,
    elevation: 16,
  },
  input: {
    shadowColor: '#c51f12',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.14,
    shadowRadius: 6,
    elevation: 2,
  },
} as const;
