// Mirrors Design.md frontmatter. Do not hardcode hex values elsewhere.
export const Colors = {
  surface: '#f9f9ff',
  surfaceDim: '#dcd9d9',
  surfaceBright: '#f9f9ff',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f6f3f2',
  surfaceContainer: '#f0eded',
  surfaceContainerHigh: '#eae7e7',
  surfaceContainerHighest: '#e5e2e1',
  onSurface: '#1c1b1b',
  onSurfaceVariant: '#59413d',
  inverseSurface: '#313030',
  inverseOnSurface: '#f3f0ef',
  outline: '#8d706c',
  outlineVariant: '#e1bfb9',
  surfaceTint: '#b02d21',
  primary: '#9e2016',
  onPrimary: '#ffffff',
  primaryContainer: '#c0392b',
  onPrimaryContainer: '#ffe5e1',
  inversePrimary: '#ffb4a9',
  secondary: '#735c00',
  onSecondary: '#ffffff',
  secondaryContainer: '#fed65b',
  onSecondaryContainer: '#745c00',
  tertiary: '#005875',
  onTertiary: '#ffffff',
  tertiaryContainer: '#007296',
  onTertiaryContainer: '#d3eeff',
  error: '#ba1a1a',
  onError: '#ffffff',
  errorContainer: '#ffdad6',
  onErrorContainer: '#93000a',
  primaryFixed: '#ffdad5',
  primaryFixedDim: '#ffb4a9',
  onPrimaryFixed: '#410000',
  onPrimaryFixedVariant: '#8e130c',
  secondaryFixed: '#ffe088',
  secondaryFixedDim: '#e9c349',
  onSecondaryFixed: '#241a00',
  onSecondaryFixedVariant: '#574500',
  tertiaryFixed: '#c0e8ff',
  tertiaryFixedDim: '#80d0f8',
  onTertiaryFixed: '#001e2b',
  onTertiaryFixedVariant: '#004d66',
  background: '#f9f9ff',
  onBackground: '#1c1b1b',
  surfaceVariant: '#e5e2e1',
} as const;

export const Shadow = {
  card: {
    shadowColor: '#9e2016',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 2,
  },
  fab: {
    shadowColor: '#9e2016',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 6,
  },
  sheet: {
    shadowColor: '#1c1b1b',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.10,
    shadowRadius: 24,
    elevation: 16,
  },
  input: {
    shadowColor: '#9e2016',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 2,
  },
} as const;
