export const Colors = {
  surface: '#fff7ef',
  surfaceDim: '#ead7cc',
  surfaceBright: '#fffdf8',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#fff0e3',
  surfaceContainer: '#ffe4d2',
  surfaceContainerHigh: '#ffd3ba',
  surfaceContainerHighest: '#ffc1a0',
  onSurface: '#211b18',
  onSurfaceVariant: '#654138',
  inverseSurface: '#2f2926',
  inverseOnSurface: '#f7f3eb',
  outline: '#9a6a5d',
  outlineVariant: '#f0c3b5',
  surfaceTint: '#c21a10',
  primary: '#c91f14',
  onPrimary: '#ffffff',
  primaryContainer: '#bb170e',
  onPrimaryContainer: '#fff1eb',
  inversePrimary: '#ffb4a8',
  secondary: '#9a6500',
  onSecondary: '#ffffff',
  secondaryContainer: '#ffe36d',
  onSecondaryContainer: '#422d00',
  tertiary: '#007f73',
  onTertiary: '#ffffff',
  tertiaryContainer: '#c8fff5',
  onTertiaryContainer: '#003b35',
  error: '#ba1a1a',
  onError: '#ffffff',
  errorContainer: '#ffdad6',
  onErrorContainer: '#93000a',
  primaryFixed: '#ffe0d9',
  primaryFixedDim: '#ffb7ac',
  onPrimaryFixed: '#410001',
  onPrimaryFixedVariant: '#8e140a',
  secondaryFixed: '#fff0a3',
  secondaryFixedDim: '#e9d35a',
  onSecondaryFixed: '#231b00',
  onSecondaryFixedVariant: '#584200',
  tertiaryFixed: '#ffdad7',
  tertiaryFixedDim: '#e9a5a1',
  onTertiaryFixed: '#3f1412',
  onTertiaryFixedVariant: '#7f2c2b',
  background: '#fff3e8',
  onBackground: '#211b18',
  surfaceVariant: '#f6d6c9',
  success: '#2e7d32',
  successContainer: '#dff2d8',
  onSuccessContainer: '#17451a',
  warning: '#f97316',
  warningContainer: '#ffedd5',
  onWarningContainer: '#7c2d12',
  deal: '#ff5a1f',
  dealContainer: '#fff0e8',
  onDealContainer: '#7a1f00',
  accentBlue: '#2563eb',
  accentBlueContainer: '#dbeafe',
  onAccentBlueContainer: '#0f2f72',
  accentPink: '#db2777',
  accentPinkContainer: '#ffe4f0',
  onAccentPinkContainer: '#70103d',
} as const;

export const Shadow = {
  card: {
    shadowColor: '#211b18',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.07,
    shadowRadius: 18,
    elevation: 2,
  },
  fab: {
    shadowColor: '#c91f14',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.22,
    shadowRadius: 18,
    elevation: 6,
  },
  sheet: {
    shadowColor: '#211b18',
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.14,
    shadowRadius: 28,
    elevation: 16,
  },
  input: {
    shadowColor: '#c91f14',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.14,
    shadowRadius: 6,
    elevation: 2,
  },
} as const;
